import { Flex, Text, Heading } from "@chakra-ui/react";
import Head from "next/head";

import { Info } from "../components/Info";
import Slider from "../components/Slider";
import { TravelTypes } from "../components/TravelTypes";

interface HomeProps {
  continents:{
    slug: string;
    title: string;
    summary: string;
    image: string;
  }[]
}

export default function Home({ continents }: HomeProps) {
  return (
    <>
      <Head>
        <title>Home | wordtrip</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Info />
      <TravelTypes />
      <Flex direction="column" align="center" justifyContent="center">
        <Text letterSpacing="-4px" fontSize="2xl" >{"--------"}</Text>
        <Heading mt="8" fontSize="2xl" fontWeight="medium">Vamos nessa?</Heading>
        <Heading mt="5" fontSize="2xl" fontWeight="medium">Então escolha seu continente</Heading>
      </Flex>
      <Slider continents={continents} />
    </>
  );
}
