import Head from 'next/head'
import { Info } from '../components/Info'
import { TravelTypes } from '../components/TravelTypes'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home | wordtrip</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Info />
      <TravelTypes />
    </div>
  )
}
