import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home | wordtrip</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Hello world</h1>
    </div>
  )
}
